Repository snapshot-labs/snapshot-spaces, pull requests merged in 2020-11, with the labels that each got.

#399 Added PoolTogether space
  skins/pooltogether.scss
  spaces/domains.json
  spaces/pooltogether/index.json
  spaces/pooltogether/logo.png
  spaces/pooltogether/space.png
Labels: domain, ready to merge

#402 view update
  spaces/yam/index.json
Labels: ready to merge

#401 Add PRIA space
  spaces/pria/index.json
  spaces/pria/logo.png
  spaces/pria/space.png
Labels: invalid

#408 Add SEEN space
  spaces/seen/index.json
  spaces/seen/logo.png
  spaces/seen/space.png
Labels: ready to merge

#409 add CULTURE space
  spaces/culture/index.json
  spaces/culture/logo.png
  spaces/culture/space.png
Labels: ready to merge

#354 Add custom domain to tballiance
  skins/tballiance.scss
  spaces/domains.json
  spaces/tballiance/index.json
Labels: domain, ready to merge

#382 Update cream space
  spaces/cream/index.json
Labels: ready to merge, strategies

#407 add ROT space
  skins/rot.scss
  spaces/domains.json
  spaces/rot/index.json
  spaces/rot/logo.png
  spaces/rot/space.png
Labels: ready to merge, strategies

#403 Add space for Rari Capital
  skins/rari.scss
  spaces/domains.json
  spaces/rari/index.json
  spaces/rari/logo.png
  spaces/rari/space.png
Labels: domain, standby, strategies

#410 Add METRIC space
  spaces/metric/index.json
  spaces/metric/logo.png
  spaces/metric/space.png
Labels: ready to merge

#412 Nov2 registry rly
  spaces/rally/index.json
Labels: ready to merge

#411 Add bloody space
  skins/bloody.scss
  spaces/bloody/index.json
  spaces/bloody/logo.png
  spaces/bloody/space.png
  spaces/domains.json
Labels: domain, ready to merge, strategies

#413 SpringDAO
  spaces/spring-dao/index.json
  spaces/spring-dao/logo.png
  spaces/spring-dao/space.png
Labels: ready to merge

#416 add mee
  skins/mee.scss
  spaces/mee/index.json
  spaces/mee/logo.png
  spaces/mee/space.png
Labels: ready to merge

#418 Update mee.scss
  skins/mee.scss
Labels: ready to merge

#419 Add Index domain
  spaces/domains.json
  spaces/index/index.json
Labels: domain, ready to merge

#417 Rly strategy v1
  spaces/rally/index.json
Labels: ready to merge, standby, strategies

#426 Add GRO space
  skins/growthdefi.scss
  spaces/growthdefi/index.json
  spaces/growthdefi/logo.png
  spaces/growthdefi/space.png
Labels: ready to merge

#427 Add Space for unFederal Reserve (PR)
  skins/unfederalreserve.scss
  spaces/unfederalreserve/index.json
  spaces/unfederalreserve/logo.png
  spaces/unfederalreserve/space.png
Labels: ready to merge

#433 add cofix space
  skins/cofix.scss
  spaces/cofix/index.json
  spaces/cofix/logo.png
  spaces/cofix/space.png
Labels: ready to merge

#420 Update DIAData Space
  skins/diadata.scss
  spaces/diadata/index.json
  spaces/domains.json
Labels: domain, ready to merge, strategies

#431 (PR) Style Edits for unFederal Reserve
  skins/unfederalreserve.scss
Labels: invalid

#439 Add iwan space
  spaces/iwan/index.json
  spaces/iwan/logo.png
  spaces/iwan/space.png
Labels: ready to merge

#437 Update DIAData space
  skins/diadata.scss
  spaces/diadata/index.json
  spaces/domains.json
Labels: invalid

#423 Add space for MANTRA DAO
  skins/mantra-dao.scss
  spaces/mantra-dao/index.json
  spaces/mantra-dao/logo.png
  spaces/mantra-dao/space.png
Labels: ready to merge, strategies

#438 Add GRO space
  spaces/growthdefi/index.json
Labels: ready to merge

#442 Update AdEx Network space: add members
  spaces/adex/index.json
Labels: ready to merge

#441 Add YUAN space
  spaces/yuan/index.json
  spaces/yuan/logo.png
  spaces/yuan/space.png
Labels: ready to merge, standby, strategies

#440 Add GAMER space
  skins/gamer.scss
  spaces/gamer/index.json
  spaces/gamer/logo.png
  spaces/gamer/space.png
Labels: ready to merge, standby, strategies

#444 Add GRO space
  skins/growthdefi.scss
  spaces/growthdefi/index.json
Labels: ready to merge

#448 Update LEX space (name, token)
  spaces/lex/index.json
Labels: ready to merge

#449 update YUAN minScore
  spaces/yuan/index.json
Labels: ready to merge

#450 Update SYMBOL and coeff of MANTRA DAO space
  spaces/mantra-dao/index.json
Labels: ready to merge

#452 [Trust] Raise proposal creation min token value
  spaces/trustwallet/index.json
Labels: ready to merge

#445 Modify pokt-network space
  spaces/pokt-network/index.json
  spaces/pokt-network/space.png
Labels: ready to merge

#451 added jibrel space
  spaces/jibrel/index.json
  spaces/jibrel/logo.png
  spaces/jibrel/space.png
Labels: ready to merge

#458 Add TRY space
  spaces/trias/index.json
  spaces/trias/logo.png
  spaces/trias/space.png
Labels: ready to merge

#461 Add yaxis domain & update strategy
  spaces/domains.json
  spaces/yaxis/index.json
Labels: domain, ready to merge

#425 Add DeFiat Space
  skins/defiat.scss
  spaces/defiat/index.json
  spaces/defiat/logo.png
  spaces/defiat/space.png
  spaces/domains.json
Labels: ready to merge, strategies

#460 pok.finance
  skins/pok.scss
  spaces/pok/index.json
  spaces/pok/logo.png
  spaces/pok/space.png
Labels: ready to merge

#462 Updated kMPL token address since it changed + adding uniswap strategy
  spaces/amplesense/index.json
Labels: ready to merge, strategies

#463 Removing wrong proposal
  spaces/decentribe/index.json
Labels: ready to merge

#454 update the index.json
  spaces/btf/index.json
Labels: ready to merge

#465 Add new member to Index space
  spaces/index/index.json
Labels: ready to merge

#468 Add QIAN space
  skins/qian.scss
  spaces/qian-bsc-testnet/index.json
  spaces/qian-bsc-testnet/logo.png
  spaces/qian-bsc-testnet/space.png
  spaces/qian-bsc/index.json
  spaces/qian-bsc/logo.png
  spaces/qian-bsc/space.png
Labels: ready to merge

#474 add invalids
  spaces/pok/index.json
Labels: ready to merge

#475 Remove proposal
  spaces/decentribe/index.json
Labels: ready to merge

#476 Add CAT5 space
  skins/hurricane.scss
  spaces/hurricane/index.json
  spaces/hurricane/logo.png
  spaces/hurricane/space.png
Labels: domain, ready to merge

#477 Logo Replacement for iyf.finance
  spaces/iyffinance/logo.png
  spaces/iyffinance/space.png
Labels: ready to merge

#478 Add custom domain for hurricane
  spaces/domains.json
Labels: domain, ready to merge

#483 Change token and symbol for dracula protocol
  spaces/dracula/index.json
Labels: ready to merge

#485 Add VLO space
  skins/velotoken.scss
  spaces/velotoken/index.json
  spaces/velotoken/logo.png
  spaces/velotoken/space.png
Labels: ready to merge

#486 Add ACS (ACryptoS) space
  spaces/acryptos/index.json
  spaces/acryptos/logo.png
  spaces/acryptos/space.png
  spaces/domains.json
Labels: domain, ready to merge

#487 Update PGT Polyient Games Governance Space
  spaces/polyient-games-governance/index.json
Labels: domain, ready to merge

#488 updates with vote.polyient.games custom domain
  spaces/domains.json
Labels: domain, ready to merge

#491 invalidate proposal
  spaces/yam/index.json
Labels: ready to merge

#493 Update LexDAO space with new token (index.json)
  spaces/lex/index.json
  spaces/lexdao/index.json
Labels: ready to merge

#496 deleting space
  spaces/jibrel/index.json
  spaces/jibrel/logo.png
  spaces/jibrel/space.png
Labels: ready to merge

#492 Aragon: Change strategies to use ANJ, add new member
  spaces/aragon/index.json
Labels: standby, strategies

#502 Aragon space: revert to old config
  spaces/aragon/index.json
Labels: ready to merge

#503 OceanDAO updates 4
  skins/oceandao.scss
  spaces/domains.json
  spaces/oceandao/index.json
  spaces/oceandao/logo.png
  spaces/oceandao/space.png
Labels: domain, ready to merge

#498 Add Frontier (FRONT) Space
  skins/frontier.scss
  spaces/domains.json
  spaces/frontier/index.json
  spaces/frontier/logo.png
  spaces/frontier/space.png
Labels: domain, ready to merge, standby, strategies

#504 added dhedge.org
  skins/dhedge.scss
  spaces/dhedge/index.json
  spaces/dhedge/logo.png
  spaces/dhedge/logo1.png
  spaces/dhedge/space.png
  spaces/domains.json
Labels: domain, ready to merge

#505 Add SAV3 space
  skins/sav3.scss
  spaces/domains.json
  spaces/sav3/index.json
  spaces/sav3/logo.png
  spaces/sav3/space.png
Labels: domain, ready to merge

#506 Add Fortube space for ethereum and rinkeby
  skins/fortube.scss
  spaces/fortube-eth/index.json
  spaces/fortube-eth/logo.png
  spaces/fortube-eth/space.png
  spaces/fortube-rinkeby/index.json
  spaces/fortube-rinkeby/logo.png
  spaces/fortube-rinkeby/space.png
Labels: ready to merge

#511 Aragon space: update symbol
  spaces/aragon/index.json
Labels: ready to merge

#509 Add ZLOT space
  skins/zlot.scss
  spaces/domains.json
  spaces/zlot/index.json
  spaces/zlot/logo.png
  spaces/zlot/space.png
Labels: domain, ready to merge

#510 Update Esprezzo space
  spaces/esprezzo/index.json
  spaces/esprezzo/skin.scss
Labels: ready to merge

#513 Add space for SCT
  skins/southchain.scss
  spaces/southchain/index.json
  spaces/southchain/logo.png
  spaces/southchain/space.png
Labels: domain, ready to merge

#507 Added debaseonomics logos,index and scss
  skins/debaseonomics.scss
  spaces/debaseonomics/index.json
  spaces/debaseonomics/logo.png
  spaces/debaseonomics/space.png
Labels: ready to merge

#508 Add 7ADD Space
  spaces/7add/index.json
  spaces/7add/logo.png
  spaces/7add/space.png
Labels: ready to merge

#515 Update QIAN invalids
  spaces/qian-bsc/index.json
  spaces/qian-eth/index.json
Labels: ready to merge

#497 Add Dawn
  skins/dawn.scss
  spaces/dawn/index.json
  spaces/dawn/space.png
  spaces/domains.json
Labels: domain, ready to merge

#516 update ForTube space name
  spaces/fortube-eth/index.json
  spaces/fortube-rinkeby/index.json
Labels: ready to merge

#517 Update ZLOT minScore to 1
  spaces/zlot/index.json
Labels: ready to merge

#518 Rly registryupdate nov19
  spaces/rally/index.json
Labels: ready to merge

#524 Update COVER info
  spaces/cover/index.json
Labels: ready to merge

#547 update pancake strategy addresses
  spaces/pancake/index.json
Labels: ready to merge

#548 Add IDLE space
  spaces/idlefinance.eth/logo.png
  spaces/idlefinance.eth/space.png
Labels: ready to merge

#543 update FinNexus space strategy and added skin
  skins/fnx.scss
  spaces/domains.json
  spaces/finnexus/index.json
Labels: domain, ready to merge

#542 Fix incorrect space <> domain
  spaces/domains.json
  spaces/synthetixproposal/index.json
Labels: invalid

#553 fix: update pancake chef address
  spaces/pancake/index.json
Labels: ready to merge

#555 Add IDLE domain
  spaces/domains.json
Labels: domain, ready to merge

#557 add invalids
  spaces/oceandao/index.json
Labels: ready to merge

#554 Add ESD Space
  spaces/domains.json
  spaces/esd.eth/logo.png
  spaces/esd.eth/space.png
Labels: domain, ready to merge

#559 Update SCT domain, skins, logo.png and space.png
  spaces/domains.json
  spaces/vote.southchain.eth/logo.png
  spaces/vote.southchain.eth/space.png
Labels: domain, ready to merge

#560 Make a test proposal hidden
  spaces/zzz-finance/index.json
Labels: ready to merge

#561 ADD Flow Community Space
  spaces/flowcommunity.eth/logo.png
  spaces/flowcommunity.eth/space.png
Labels: ready to merge

#563 Add PROPHET space
  spaces/prophetfinance.eth/logo.png
  spaces/prophetfinance.eth/space.png
Labels: ready to merge

#564 Add ARCH archerdao.eth
  spaces/archerdao.eth/logo.png
  spaces/archerdao.eth/space.png
Labels: ready to merge
