Repository snapshot-labs/snapshot-spaces, pull requests merged in 2020-09, with the labels that each got.

#82 Add ROBOT space
  spaces/metafactory/index.json
  spaces/metafactory/logo.png
  spaces/metafactory/skin.scss
  spaces/metafactory/space.png
Labels: Ready to merge

#77 Add $WAGE space
  spaces/wage/index.json
  spaces/wage/logo.png
  spaces/wage/space.png
Labels: Ready to merge

#75 Add ROT space
  spaces/rotten-swap/index.json
  spaces/rotten-swap/logo.png
  spaces/rotten-swap/skin.scss
  spaces/rotten-swap/space.png
Labels: Ready to merge

#74 ADD DEGO space
  spaces/dego/index.json
  spaces/dego/logo.png
  spaces/dego/space.png
Labels: Ready to merge

#71 Add GOF space
  spaces/golff/index.json
  spaces/golff/logo.png
  spaces/golff/skin.scss
  spaces/golff/space.png
Labels: Ready to merge

#67 Add 0xDollar space
  spaces/0xdollar/index.json
  spaces/0xdollar/logo.png
  spaces/0xdollar/space.png
Labels: Ready to merge

#62 Add CREED space
  spaces/creed/index.json
  spaces/creed/logo.png
  spaces/creed/space.png
Labels: Ready to merge

#56 Add REB2 space
  spaces/reb2/index.json
  spaces/reb2/logo.png
  spaces/reb2/space.png
Labels: Ready to merge

#34 Add MOONEVD space
  spaces/moonswap/index.json
  spaces/moonswap/logo.png
  spaces/moonswap/skin.scss
  spaces/moonswap/space.png
Labels: Ready to merge

#10 Add PAYRUE space
  spaces/payrue/index.json
  spaces/payrue/logo.png
  spaces/payrue/space.png
Labels: invalid

#87 Add TON space
  spaces/ton/index.json
  spaces/ton/logo.png
  spaces/ton/space.png
Labels: ready to merge

#63 Add PCT V space
  spaces/percent/index.json
  spaces/percent/logo.png
  spaces/percent/space.png
Labels: ready to merge

#78 Edit Sake Address
  spaces/sake/index.json
Labels: ready to merge

#72 Edit Dollar Protocol space
  spaces/dollar-protocol/index.json
  spaces/dollar-protocol/logo.png
Labels: ready to merge

#45 add ADEL space
  spaces/akropolis-delphi/index.json
  spaces/akropolis-delphi/logo.png
  spaces/akropolis-delphi/logo1.png
  spaces/akropolis-delphi/skin.scss
  spaces/akropolis-delphi/space.png
Labels: invalid

#61 Edit LONGPOWER contract address
  spaces/long/index.json
Labels: ready to merge

#91 UPDATE ROT space URL
  spaces/rotten/index.json
  spaces/rotten/logo.png
  spaces/rotten/skin.scss
  spaces/rotten/space.png
Labels: ready to merge

#92 Add DANIMESQ space
  spaces/daniell-mesquita/index.json
  spaces/daniell-mesquita/logo.png
  spaces/daniell-mesquita/skin.scss
  spaces/daniell-mesquita/space.png
Labels: ready to merge

#96 add ampleforth
  spaces/ampleforth/index.json
  spaces/ampleforth/logo.png
  spaces/ampleforth/skin.scss
  spaces/ampleforth/space.png
Labels: ready to merge

#103 Add GRG space
  spaces/rigoblock/index.json
  spaces/rigoblock/logo.png
  spaces/rigoblock/space.png
Labels: ready to merge

#89 Add MTA space
  spaces/mstable/index.json
  spaces/mstable/logo.png
  spaces/mstable/skin.scss
  spaces/mstable/space.png
Labels: ready to merge

#84 Add YAX space
  spaces/yaxis/index.json
  spaces/yaxis/logo.png
  spaces/yaxis/skin.scss
  spaces/yaxis/space.png
Labels: ready to merge

#104 Add space for Trips
  spaces/tripscommunity/index.json
  spaces/tripscommunity/logo.png
  spaces/tripscommunity/skin.scss
  spaces/tripscommunity/space.png
Labels: ready to merge

#109 Add AMPLG space
  spaces/amplegold/index.json
  spaces/amplegold/logo.png
  spaces/amplegold/space.png
Labels: ready to merge

#95 edit sccc and strategies
  spaces/golff/index.json
  spaces/golff/skin.scss
Labels: ready to merge, strategies

#66 Edit FARM strategies
  spaces/farm/index.json
Labels: ready to merge, strategies

#111 Add MEW space
  spaces/mew/index.json
  spaces/mew/logo.png
  spaces/mew/space.png
Labels: ready to merge

#118 Edit $Based space
  spaces/based/index.json
  spaces/based/skin.scss
Labels: ready to merge

#127 Add GALAXY space
  spaces/galaxy/index.json
  spaces/galaxy/logo.png
  spaces/galaxy/space.png
Labels: ready to merge

#102 Add dForce space
  spaces/dforce/index.json
  spaces/dforce/logo.png
  spaces/dforce/skin.scss
  spaces/dforce/space.png
Labels: ready to merge

#108 Add SFG space
  spaces/domains.json
  spaces/s-finance/index.json
  spaces/s-finance/logo.png
  spaces/s-finance/space.png
Labels: domain, ready to merge

#129 Add AST space
  spaces/airswap/index.json
  spaces/airswap/logo.png
  spaces/airswap/skin.scss
  spaces/airswap/space.png
  spaces/domains.json
Labels: domain, ready to merge

#138 Add cUNI space
  spaces/cuni/index.json
  spaces/cuni/logo.png
  spaces/cuni/space.png
Labels: ready to merge

#139 Add XPZ space
  spaces/esprezzo/index.json
  spaces/esprezzo/logo.png
  spaces/esprezzo/skin.scss
  spaces/esprezzo/space.png
Labels: ready to merge

#137 add CREAM space
  spaces/cream/index.json
  spaces/cream/logo.png
  spaces/cream/space.png
Labels: ready to merge

#133 Rinkeby
  spaces/oaklanddao/index.json
  spaces/oaklanddao/logo.png
  spaces/oaklanddao/skin.scss
  spaces/oaklanddao/space.png
Labels: ready to merge

#128 Add FairSwap.farm space
  spaces/fairswap/index.json
  spaces/fairswap/logo.png
  spaces/fairswap/skin.css
  spaces/fairswap/space.png
Labels: ready to merge

#110 Add DANIMESQ-XDAI space
  spaces/daniell-mesquita-xdai/index.json
  spaces/daniell-mesquita-xdai/logo.png
  spaces/daniell-mesquita-xdai/skin.scss
  spaces/daniell-mesquita-xdai/space.png
Labels: ready to merge

#135 Add WEFI space
  spaces/wolfage/index.json
  spaces/wolfage/logo.png
  spaces/wolfage/space.png
Labels: ready to merge

#115 Add Y3D space
  spaces/y3d/index.json
  spaces/y3d/logo.png
  spaces/y3d/skin.scss
  spaces/y3d/space.png
Labels: ready to merge

#124 Add CAPT space
  spaces/captain/index.json
  spaces/captain/logo.png
  spaces/captain/space.png
Labels: ready to merge

#113 Add SDOGE space
  spaces/sdoge/index.json
  spaces/sdoge/logo.png
  spaces/sdoge/space.png
Labels: ready to merge

#123 SpaceSwap Project
  spaces/spaceswap/index.json
  spaces/spaceswap/logo.png
  spaces/spaceswap/skin.scss
  spaces/spaceswap/space.png
Labels: ready to merge

#131 Add UNICOPE space
  spaces/unicope/index.json
  spaces/unicope/logo.png
  spaces/unicope/space.png
Labels: ready to merge

#134 Add TRIB space
  spaces/contribute/index.json
  spaces/contribute/logo.png
  spaces/contribute/skin.scss
  spaces/contribute/space.png
Labels: ready to merge

#142 Add DICE space
  spaces/dice/index.json
  spaces/dice/logo.png
  spaces/dice/space.png
Labels: ready to merge

#143 Updating Logo for Existing Space
  spaces/dollar-protocol/logo.png
Labels: ready to merge
