Repository snapshot-labs/snapshot-spaces, pull requests merged in 2020-10, with the labels that each got.

#120 add EGG space
  spaces/egg/index.json
  spaces/egg/logo.png
  spaces/egg/skin.scss
  spaces/egg/space.png
Labels: ready to merge

#147 add CORE space
  spaces/core/index.json
  spaces/core/logo.png
  spaces/core/space.png
Labels: ready to merge

#150 Update index.json
  spaces/unicope/index.json
Labels: ready to merge

#148 Update index.json
  spaces/unicope/index.json
Labels: ready to merge

#146 Merge to add Stabilize token to Snapshot
  spaces/stabilize/index.json
  spaces/stabilize/logo.png
  spaces/stabilize/space.png
Labels: ready to merge

#152 Add d5 space
  spaces/d5/index.json
  spaces/d5/logo.png
  spaces/d5/space.png
Labels: ready to merge

#153 Add ONCEMONEY space
  spaces/oncemoney/index.json
  spaces/oncemoney/logo.png
  spaces/oncemoney/space.png
Labels: ready to merge

#155 add invalid proposals
  spaces/yam/index.json
Labels: ready to merge

#156 update colors
  spaces/spaceswap/skin.scss
Labels: ready to merge

#157 Add custom domain for EGG
  spaces/domains.json
Labels: domain, ready to merge

#158 Update metafactory token
  spaces/metafactory/index.json
Labels: ready to merge

#160 Add WASSIES space
  spaces/wassies/index.json
  spaces/wassies/logo.png
  spaces/wassies/space.png
Labels: ready to merge

#161 Wolfage invalids.
  spaces/wolfage/index.json
Labels: ready to merge

#145 Add LEX space
  spaces/lex/index.json
  spaces/lex/logo.png
  spaces/lex/space.png
Labels: ready to merge

#164 Revert LexDAO space to Snapshot "default" skin.scss
  spaces/lexdao/skin.scss
Labels: ready to merge

#165 Add PRT space
  spaces/portion/index.json
  spaces/portion/logo.png
  spaces/portion/space.png
Labels: ready to merge

#163 added core contract
  spaces/spaceswap/index.json
  spaces/spaceswap/skin.scss
Labels: ready to merge

#162 Add YFFC space
  spaces/yffc/index.jscsrc
  spaces/yffc/logo.png
  spaces/yffc/skin.scss
  spaces/yffc/space.png
Labels: ready to merge

#168 add CHADS space
  spaces/chadsvc/index.json
  spaces/chadsvc/logo.png
  spaces/chadsvc/skin.scss
  spaces/chadsvc/space.png
Labels: ready to merge

#170 Add GMT space
  spaces/domains.json
  spaces/gmt/index.json
  spaces/gmt/logo.png
  spaces/gmt/skin.scss
  spaces/gmt/space.png
  spaces/homepage.json
Labels: domain, ready to merge

#171 Add $ROPE space
  spaces/rope/index.json
  spaces/rope/logo.png
  spaces/rope/skin.scss
  spaces/rope/space.png
Labels: ready to merge

#172 QubCoins
  spaces/qubcoins/index.json
  spaces/qubcoins/logo.png
  spaces/qubcoins/skin.scss
  spaces/qubcoins/space.png
Labels: ready to merge

#116 FARM edit strategy
  spaces/farm/index.json
  spaces/farm/logo1.png
Labels: invalid, strategies

#179 Add YFFS space
  spaces/yffs/index.json
  spaces/yffs/logo.png
  spaces/yffs/skin.scss
  spaces/yffs/space.png
Labels: ready to merge

#175 Add SLEEP space
  spaces/sleeping/index.json
  spaces/sleeping/logo.png
  spaces/sleeping/skin.scss
  spaces/sleeping/space.png
Labels: ready to merge

#189 Remove 4 redundant proposals
  spaces/mstable/index.json
Labels: ready to merge

#154 Add Sogur space
  spaces/sogur/index.json
  spaces/sogur/logo.png
  spaces/sogur/space.png
Labels: ready to merge, strategies

#188 feat: Add CAPY space
  spaces/capy/index.json
  spaces/capy/logo.png
  spaces/capy/skin.scss
  spaces/capy/space.png
Labels: ready to merge

#187 Update oaklanddao space
  spaces/domains.json
Labels: domain, ready to merge

#197 Update domains.json
  spaces/domains.json
Labels: ready to merge

#193 Add $JAMM space
  spaces/jamm/index.json
  spaces/jamm/logo.png
  spaces/jamm/space.png
Labels: ready to merge

#191 Add Trust Wallet space
  spaces/domains.json
  spaces/trust-wallet/index.json
  spaces/trust-wallet/logo.png
  spaces/trust-wallet/skin.scss
  spaces/trust-wallet/space.png
Labels: domain, ready to merge

#194 add WOLF space
  spaces/wolfdefi/index.json
  spaces/wolfdefi/logo.png
  spaces/wolfdefi/skin.scss
  spaces/wolfdefi/space.png
Labels: ready to merge

#195 add GFIN space
  spaces/griffin/index.json
  spaces/griffin/logo.png
  spaces/griffin/skin.scss
  spaces/griffin/space.png
Labels: ready to merge

#201 Add limitswap
  spaces/limitswap/index.json
  spaces/limitswap/logo.png
  spaces/limitswap/skin.scss
  spaces/limitswap/space.png
Labels: ready to merge

#202 dfi.money add a custom domain
  spaces/domains.json
Labels: domain, ready to merge

#196 add YKZ space
  spaces/domains.json
  spaces/yakuza/index.json
  spaces/yakuza/logo.png
  spaces/yakuza/skin.scss
  spaces/yakuza/space.png
Labels: domain, ready to merge

#206 Add SMOL space
  spaces/smol/index.json
  spaces/smol/logo.png
  spaces/smol/skin.scss
  spaces/smol/space.png
Labels: ready to merge

#207 Add GEM space
  spaces/cargo/index.json
  spaces/cargo/logo.png
  spaces/cargo/skin.scss
  spaces/cargo/space.png
Labels: ready to merge

#205 Add YFARM space
  spaces/yfarm/index.json
  spaces/yfarm/logo.png
  spaces/yfarm/skin.scss
  spaces/yfarm/space.png
Labels: ready to merge

#209 Update cream space
  spaces/cream/index.json
  spaces/domains.json
Labels: domain, ready to merge

#203 Edit YFII strategies - in pool3 pool4 mefi can also vote
  spaces/dfi/index.json
Labels: ready to merge, strategies

#208 sogur - add strategy 2 logo
  spaces/sogur/logo1.png
Labels: ready to merge

#210 Add 'swarm' space
  spaces/swarm/index.json
  spaces/swarm/logo.png
  spaces/swarm/skin.scss
  spaces/swarm/space.png
Labels: ready to merge

#211 Add EXNG space
  spaces/domains.json
  spaces/exnetwork/index.json
  spaces/exnetwork/logo.png
  spaces/exnetwork/space.png
Labels: domain, ready to merge

#213 Add PGT space
  spaces/polyient-games-governance/index.json
  spaces/polyient-games-governance/logo.png
  spaces/polyient-games-governance/skin.scss
  spaces/polyient-games-governance/space.png
Labels: ready to merge

#216 Add KATANA space
  spaces/katana/index.json
  spaces/katana/logo.png
  spaces/katana/space.png
Labels: ready to merge

#218 Add space for OAKM
  spaces/oaklanddao/index.json
  spaces/oaklanddao/logo.png
  spaces/oaklanddao/skin.scss
  spaces/oaklanddao/space.png
Labels: ready to merge

#219 Add space for HubDao
  spaces/hubdao/index.json
  spaces/hubdao/logo.png
  spaces/hubdao/skin.scss
  spaces/hubdao/space.png
Labels: ready to merge

#214 add SEND space
  spaces/send/index.json
  spaces/send/logo.png
  spaces/send/space.png
Labels: ready to merge

#223 Add space for Ourbloc (Dap)
  spaces/ourbloc/index.json
  spaces/ourbloc/logo.png
  spaces/ourbloc/space.png
Labels: ready to merge

#200 Adex
  spaces/adex/skin.scss
Labels: ready to merge

#224 hide test proposal
  spaces/cargo/index.json
Labels: ready to merge

#215 Update PCT space
  spaces/percent/index.json
Labels: ready to merge, standby

#236 Add invalid proposal to akropolis-delphi space
  spaces/akropolis-delphi/index.json
Labels: ready to merge

#232 Add BZRX space
  spaces/bzx/index.json
  spaces/bzx/logo.png
  spaces/bzx/space.png
Labels: invalid

#240 Add RLY space
  spaces/rally/index.json
  spaces/rally/logo.png
  spaces/rally/space.png
Labels: ready to merge

#241 Add LIGHT space
  skins/light.scss
  spaces/light/index.json
  spaces/light/logo.png
  spaces/light/space.png
Labels: ready to merge

#242 Added 4 invalid proposals
  spaces/tripscommunity/index.json
Labels: ready to merge

#246 Add PPBLZ space
  spaces/pepemon/index.json
  spaces/pepemon/logo.png
  spaces/pepemon/space.png
Labels: ready to merge

#248 Add MoonTools space
  skins/moontools.scss
  spaces/moontools/index.json
  spaces/moontools/logo.png
  spaces/moontools/space.png
Labels: ready to merge

#249 Add ZETA space
  skins/zeta.scss
  spaces/zeta/index.json
  spaces/zeta/logo.png
  spaces/zeta/space.png
Labels: ready to merge, strategies

#247 Add XFI space
  spaces/domains.json
  spaces/xfinance/index.json
  spaces/xfinance/logo.png
  spaces/xfinance/space.png
Labels: domain, ready to merge

#254 Tripscommunity - added entry to array
  spaces/tripscommunity/index.json
Labels: ready to merge

#253 add domain for pancake
  spaces/domains.json
Labels: ready to merge

#251 Add invalid proposal to yakuza space
  spaces/yakuza/index.json
Labels: ready to merge

#255 adding kmpl
  spaces/kmpl/index.json
  spaces/kmpl/logo.png
  spaces/kmpl/logo1.png
  spaces/kmpl/space.png
Labels: ready to merge, standby, strategies

#262 Update domains.json
  spaces/domains.json
Labels: domain, ready to merge

#263 Create wassies.scss
  skins/wassies.scss
Labels: ready to merge

#265 Create love.scss
  skins/love.scss
Labels: ready to merge

#266 Update index.json
  spaces/love/index.json
Labels: ready to merge

#269 Update domains.json
  spaces/domains.json
Labels: domain, ready to merge

#258 Add INDEX space
  skins/index.scss
  spaces/index/index.json
  spaces/index/logo.png
  spaces/index/space.png
Labels: ready to merge, skin

#259 Add CLV space :four_leaf_clover: (Corrected for new index.json format)
  spaces/clover/index.json
  spaces/clover/logo.png
  spaces/clover/space.png
Labels: ready to merge

#268 Update index.json
  spaces/ourbloc/index.json
Labels: ready to merge

#272 Add NEST space
  skins/nest.scss
  spaces/nest/index.json
  spaces/nest/logo.png
  spaces/nest/space.png
Labels: ready to merge, skin

#274 Add Mettalex space
  skins/mettalex.scss
  spaces/mettalex/index.json
  spaces/mettalex/logo.png
  spaces/mettalex/space.png
Labels: ready to merge, skin

#252 Update pancake space for new strategy
  spaces/pancake/index.json
Labels: invalid, strategies

#273 Add SWAGG space
  skins/swagg.scss
  spaces/swagg/index.json
  spaces/swagg/logo.png
  spaces/swagg/space.png
Labels: ready to merge, skin

#277 Update PCT
  spaces/percent/index.json
Labels: ready to merge

#278 changing kml page name + core address + page logo
  spaces/kmpl/index.json
  spaces/kmpl/space.png
Labels: ready to merge

#282 Mettalex domain new skin
  skins/mettalex.scss
  spaces/domains.json
  spaces/mettalex/logo.png
  spaces/mettalex/space.png
Labels: domain, ready to merge, skin

#283 Add ENB space
  spaces/earnbase/index.json
  spaces/earnbase/logo.png
  spaces/earnbase/space.png
Labels: ready to merge

#279 add RDAO space
  spaces/rdao/index.json
  spaces/rdao/logo.png
  spaces/rdao/space.png
Labels: ready to merge

#285 Update MoonTools space
  skins/moontools.scss
  spaces/domains.json
Labels: ready to merge

#280 Add BTF space
  spaces/btf/index.json
  spaces/btf/logo.png
  spaces/btf/space.png
Labels: ready to merge

#287 add fry.world space
  skins/fries.scss
  spaces/fries/index.json
  spaces/fries/logo.png
  spaces/fries/space.png
Labels: ready to merge, skin

#289 iyf.finance
  skins/iyffinance.scss
  spaces/iyffinance/index.json
  spaces/iyffinance/logo.png
  spaces/iyffinance/space.png
Labels: ready to merge, skin

#290 add Seal space
  spaces/seal/index.json
  spaces/seal/logo.png
  spaces/seal/space.png
Labels: ready to merge

#281 Web3API Snapshot Space
  skins/web3-api.scss
  spaces/web3-api/index.json
  spaces/web3-api/logo.png
  spaces/web3-api/space.png
Labels: ready to merge, skin

#288 TOAST space updated
  spaces/toast/index.json
Labels: ready to merge

#301 add pancake domain && update strategy
  spaces/domains.json
  spaces/pancake/index.json
Labels: domain, ready to merge

#302 Adding new RLY Registrants
  spaces/rally/index.json
Labels: ready to merge

#296 add TACO space
  spaces/domains.json
  spaces/taco/index.json
  spaces/taco/logo.png
  spaces/taco/space.png
Labels: domain, ready to merge

#304 TOAST space updated
  spaces/toast/index.json
Labels: ready to merge

#313 Add NARHOLDERS space
  skins/narwhal.scss
  spaces/narwhal/index.json
  spaces/narwhal/logo.png
  spaces/narwhal/space.png
Labels: domain, ready to merge

#314 Add NARHOLDERS space
  spaces/domains.json
Labels: domain, ready to merge

#315 added CARTEL
  spaces/cartel/index.json
  spaces/cartel/logo.png
  spaces/cartel/space.png
Labels: ready to merge

#318 Add $CHEIV space
  skins/achievmintry.scss
  spaces/achievmintry/index.json
  spaces/achievmintry/logo.png
  spaces/achievmintry/space.png
Labels: ready to merge

#320 Add SAFE2 space
  spaces/safe2/index.json
  spaces/safe2/logo.png
  spaces/safe2/space.png
Labels: ready to merge

#321 update NARHOLDERS invalids
  spaces/narwhal/index.json
Labels: ready to merge

#322 Use abbreviation
  spaces/synthetix/index.json
Labels: ready to merge

#323 v2 update with style changes
  skins/fries.scss
  spaces/fries/index.json
Labels: ready to merge

#316 Add ZZZ space
  spaces/zzz-finance/index.json
  spaces/zzz-finance/logo.png
  spaces/zzz-finance/space.png
Labels: ready to merge, strategies

#324 Add ALPHA space
  skins/alpha.scss
  spaces/alpha/index.json
  spaces/alpha/logo.png
  spaces/alpha/space.png
Labels: ready to merge

#325 update sake voter-address and add sake members address
  spaces/sake/index.json
Labels: ready to merge

#297 Add UniCore Space
  skins/unicore.scss
  spaces/domains.json
  spaces/unicore/index.json
  spaces/unicore/logo.png
  spaces/unicore/space.png
Labels: domain, ready to merge, skin

#329 renaming kmpl to amplesense + new format
  spaces/amplesense/index.json
  spaces/amplesense/logo.png
  spaces/amplesense/logo1.png
  spaces/amplesense/space.png
  spaces/domains.json
  spaces/kmpl/space.png
Labels: ready to merge

#330 Update index.json
  spaces/mstable/index.json
Labels: ready to merge

#309 PayRue Space Changes
  spaces/payrue/index.json
Labels: ready to merge

#332 Add core addresses and default label to "core"
  spaces/synthetix/index.json
Labels: ready to merge

#337 Adding DNLD space (fixed?)
  skins/music.scss
  spaces/music/index.json
  spaces/music/logo.png
  spaces/music/space.png
Labels: ready to merge

#341 Update token info for fry.world
  spaces/fries/index.json
Labels: ready to merge

#338 Add LCORE space
  spaces/lcore/index.json
  spaces/lcore/logo.png
  spaces/lcore/space.png
Labels: ready to merge

#342 Add ETGF space
  skins/etgfinance.scss
  spaces/etgfinance/index.json
  spaces/etgfinance/logo.png
  spaces/etgfinance/space.png
Labels: ready to merge

#343 Add ChartEx Space
  skins/chartex.scss
  spaces/chartex/index.json
  spaces/chartex/logo.png
  spaces/chartex/space.png
  spaces/domains.json
Labels: domain, ready to merge

#345 colors update
  skins/yam.scss
Labels: ready to merge

#346 token info update
  spaces/fries/index.json
Labels: ready to merge

#347 Add TENS space
  spaces/tenspeed/index.json
  spaces/tenspeed/logo.png
  spaces/tenspeed/space.png
Labels: ready to merge

#326 Add tballiance space
  skins/tballiance.scss
  spaces/tballiance/index.json
  spaces/tballiance/logo.png
  spaces/tballiance/space.png
Labels: ready to merge

#356 Add space for Penguin Party 🐟
  skins/penguin-party.scss
  spaces/penguin-party/index.json
  spaces/penguin-party/logo.png
  spaces/penguin-party/space.png
Labels: ready to merge

#355 Add Tokenlon space
  spaces/tokenlon/index.json
  spaces/tokenlon/logo.png
  spaces/tokenlon/space.png
Labels: invalid

#339 adding decentribe space
  spaces/decentribe/index.json
  spaces/decentribe/logo.png
  spaces/decentribe/space.png
Labels: ready to merge

#359 add Gene Finance snapshot page
  skins/gene-finance.scss
  spaces/gene-finance/index.json
  spaces/gene-finance/logo.png
  spaces/gene-finance/space.png
Labels: ready to merge

#360 update strategy chef for pancake
  spaces/pancake/index.json
Labels: ready to merge

#350 Add zacfinance space
  spaces/zacfinance/index.json
  spaces/zacfinance/logo.png
  spaces/zacfinance/space.png
Labels: ready to merge

#362 Voting weight error correction
  spaces/amplesense/index.json
Labels: ready to merge

#364 Rally ray
  spaces/rally/index.json
Labels: ready to merge

#366 Add DRC space
  skins/dracula.scss
  spaces/dracula/index.json
  spaces/dracula/logo.png
  spaces/dracula/space.png
Labels: ready to merge

#361 Update zzz onlyMembers parameter
  spaces/zzz-finance/index.json
Labels: ready to merge

#291 Add strategies for cream space
  spaces/cream/index.json
Labels: invalid, strategies

#370 Update TRIB space (scss)
  skins/contribute.scss
Labels: ready to merge

#377 Added new Core Member ETH address
  spaces/digital-reserve-currency/index.json
Labels: ready to merge

#381 Add ALPHA (BSC) space
  spaces/alpha-bsc/index.json
  spaces/alpha-bsc/logo.png
  spaces/alpha-bsc/space.png
Labels: ready to merge

#380 Update ALPHA space to specific for Ethereum
  spaces/alpha-ethereum/index.json
  spaces/alpha-ethereum/logo.png
  spaces/alpha-ethereum/space.png
Labels: ready to merge

#349 Update cuni strategy to use cToken strategy
  spaces/cuni/index.json
Labels: strategies

#373 Add NICE space
  skins/nice.scss
  spaces/domains.json
  spaces/nice/index.json
  spaces/nice/logo.png
  spaces/nice/space.png
Labels: domain, ready to merge, strategies

#374 Add DATA space
  skins/streamr.scss
  spaces/domains.json
  spaces/streamr/index.json
  spaces/streamr/logo.png
  spaces/streamr/space.png
Labels: domain, ready to merge

#385 add a gene dev address
  spaces/gene-finance/index.json
Labels: ready to merge

#368 Update zzz, add invalids
  spaces/zzz-finance/index.json
Labels: ready to merge, strategies

#389 clean some tests proposals
  spaces/gene-finance/index.json
Labels: ready to merge

#378 Update space for WolfDeFi
  spaces/wolfdefi/index.json
Labels: ready to merge, strategies

#391 add PLA space
  spaces/plasmmer-xdai/index.json
  spaces/plasmmer-xdai/logo.png
  spaces/plasmmer-xdai/space.png
Labels: ready to merge

#394 Remove rotten space
  skins/rotten.scss
  spaces/rotten/index.json
  spaces/rotten/logo.png
  spaces/rotten/space.png
Labels: ready to merge

#395 Remove rotten-swap space
  skins/rotten-swap.scss
  spaces/rotten-swap/index.json
  spaces/rotten-swap/logo.png
  spaces/rotten-swap/space.png
Labels: ready to merge

#384 Add DIAData Space
  skins/diadata.scss
  spaces/diadata/index.json
  spaces/diadata/logo.png
  spaces/diadata/space.png
  spaces/domains.json
Labels: domain, ready to merge
