Repository snapshot-labs/snapshot-spaces, pull requests merged in 2020-12, with the labels that each got.

#562 Add PAPER space
  skins/flush.scss
  spaces/domains.json
  spaces/flushlol.eth/logo.png
  spaces/flushlol.eth/space.png
Labels: domain, ready to merge

#540 Updated members in 'swarm' workspace
  spaces/swarm/index.json
  spaces/swarmnetwork.eth/logo.png
  spaces/swarmnetwork.eth/space.png
Labels: ready to merge

#571 truegov.eth space
  spaces/truegov.eth/logo.png
  spaces/truegov.eth/space.png
Labels: ready to merge

#573 Add space and default strategy logos
  spaces/xionetwork.eth/logo.png
  spaces/xionetwork.eth/space.png
Labels: ready to merge

#574 Add KP2R Space
  spaces/domains.json
  spaces/keep2r.eth/logo.png
  spaces/keep2r.eth/space.png
Labels: domain, ready to merge

#569 Add ARCH custom domain
  spaces/domains.json
Labels: domain, ready to merge, standby

#576 Add images to xethfinance.eth space
  spaces/xethfinance.eth/logo.png
  spaces/xethfinance.eth/space.png
Labels: ready to merge

#578 Add images for Tradersquare ($TRS)
  spaces/tradersquare.eth/logo.png
  spaces/tradersquare.eth/space.png
Labels: ready to merge

#556 Add Meter spaces
  spaces/domains.json
  spaces/meter-eth.eth/logo.png
  spaces/meter-eth.eth/logo1.png
  spaces/meter-eth.eth/logo2.png
  spaces/meter-eth.eth/space.png
  spaces/meter-mainnet.eth/logo.png
  spaces/meter-mainnet.eth/space.png
Labels: domain, ready to merge

#579 Add GRO space
  spaces/growthdefi/index.json
Labels: ready to merge

#580 Update Penguin Party Strategy
  spaces/penguin-party/index.json
Labels: ready to merge

#572 Index: Update strategy to read from unclaimed Index balance
  spaces/index/index.json
Labels: ready to merge, standby, strategies

#586 Remove old proposals
  spaces/finnexus/index.json
Labels: ready to merge

#592 Update domains.json and add space logo and strategy image
  spaces/domains.json
  spaces/metapoolgov.eth/logo.png
  spaces/metapoolgov.eth/space.png
Labels: domain, ready to merge

#588 Add MOL space
  spaces/moltenfinance.eth/logo.png
  spaces/moltenfinance.eth/space.png
Labels: ready to merge

#581 Add BADGER Space
  skins/badger.scss
  spaces/badgerdao.eth/logo.png
  spaces/badgerdao.eth/space.png
Labels: invalid

#593 Add GOKAI space
  skins/gokai.scss
  spaces/domains.json
  spaces/gokai.eth/logo.png
  spaces/gokai.eth/space.png
Labels: ready to merge

#600 invalidate
  spaces/yam/index.json
Labels: ready to merge

#589 add BT spaces
  spaces/btfinance.eth/logo.png
  spaces/btfinance.eth/space.png
  spaces/domains.json
Labels: domain, ready to merge

#604 Add files via upload
  spaces/xionetwork.eth/logo1.png
Labels: ready to merge

#598 decentralgames space
  spaces/decentralgames.eth/logo.png
  spaces/decentralgames.eth/space.png
Labels: ready to merge

#605 Update Contract Information
  spaces/hurricane/index.json
Labels: invalid

#610 Added strategies to our DRC Space
  spaces/digital-reserve-currency/index.json
Labels: ready to merge, strategies

#609 Add images and domain info for Honey Finance (honeyfinance.eth)
  spaces/domains.json
  spaces/honeyfinance.eth/logo.png
  spaces/honeyfinance.eth/space.png
Labels: domain, ready to merge

#614 Added 2 invalids to Digital Reserve Currency Space
  spaces/digital-reserve-currency/index.json
Labels: ready to merge

#615 update core
  spaces/yam/index.json
Labels: ready to merge

#612 baovotes.eth
  spaces/baovotes.eth/logo.png
  spaces/baovotes.eth/space.png
Labels: ready to merge

#565 Add GDS space
  skins/nftgoddess.scss
  spaces/domains.json
  spaces/nftgoddessart.eth/logo.png
  spaces/nftgoddessart.eth/space.png
Labels: domain, ready to merge

#619 Add logos for wse.eth spaces
  spaces/wse.eth/logo.png
  spaces/wse.eth/space.png
Labels: ready to merge

#582 Add Midas Space
  spaces/midas-defi.eth/logo.png
  spaces/midas-defi.eth/space.png
Labels: ready to merge

#621 add COL space
  skins/unitprotocol.scss
  spaces/unitprotocol.eth/logo.png
  spaces/unitprotocol.eth/space.png
Labels: ready to merge

#623 try3
  spaces/yfdfi.eth/logo.png
  spaces/yfdfi.eth/logo1.png
  spaces/yfdfi.eth/space.png
Labels: ready to merge

#625 Add ubtx.eth logos
  spaces/ubxt.eth/logo.png
  spaces/ubxt.eth/space.png
Labels: ready to merge

#628 Critical update to the Rari Capital space
  spaces/rari/index.json
Labels: ready to merge, strategies

#629 change COL color
  skins/unitprotocol.scss
Labels: ready to merge

#611 Add DSGN space
  skins/dsgn.scss
  spaces/wearedesign.eth/logo.png
  spaces/wearedesign.eth/space.png
Labels: ready to merge

#631 update earndeficoin.eth logo
  spaces/earndeficoin.eth/logo.png
  spaces/earndeficoin.eth/space.png
Labels: ready to merge

#633 Add governance domain for relayer network
  spaces/domains.json
Labels: domain, ready to merge

#635 added logo for tranche.eth
  spaces/tranche.eth/logo.png
  spaces/tranche.eth/space.png
Labels: ready to merge

#632 Add multiplierfinance.eth space
  skins/multiplier.scss
  spaces/domains.json
  spaces/multiplierfinance.eth/logo.png
  spaces/multiplierfinance.eth/space.png
Labels: invalid

#638 Update GOKAI skin
  skins/gokai.scss
Labels: ready to merge

#641 Add TRI space
  spaces/trinityprotocol.eth/logo.png
  spaces/trinityprotocol.eth/space.png
Labels: ready to merge

#630 Enable 2nd INDEX rewards pool for Snapshot voting
  spaces/index/index.json
Labels: ready to merge, strategies

#642 yfi3money.eth
  spaces/yfi3money.eth/logo.png
  spaces/yfi3money.eth/space.png
Labels: ready to merge

#643 add cover protocol custom domain and raise score
  spaces/cover/index.json
  spaces/domains.json
Labels: domain, ready to merge

#645 Add uniqueone.eth space
  spaces/domains.json
  spaces/uniqueone.eth/logo.png
  spaces/uniqueone.eth/space.png
Labels: domain, ready to merge

#649 Add snapshot.puul.eth
  spaces/snapshot.puul.eth/logo.png
  spaces/snapshot.puul.eth/space.png
Labels: invalid

#648 Add YUP Space
  skins/yup.scss
  spaces/yup.eth/logo.png
  spaces/yup.eth/space.png
Labels: ready to merge

#650 Add BasisCash Space
  spaces/basiscash.eth/logo.png
  spaces/basiscash.eth/space.png
  spaces/domains.json
Labels: domain, ready to merge

#652 Add D3FI Voting
  spaces/vote.defi3dot0.eth/logo.png
  spaces/vote.defi3dot0.eth/space.png
Labels: ready to merge

#653 Reduce minscore from 1,000 to 1.
  spaces/reb2/index.json
Labels: ready to merge

#651 Add balance of yYFL strategy
  spaces/yflink/index.json
Labels: ready to merge, strategies

#654 Add KEYFI space
  skins/keyfi.scss
  spaces/keyfi-app.eth/logo.png
  spaces/keyfi-app.eth/space.png
Labels: ready to merge

#644 Add_KFI
  spaces/domains.json
  spaces/keeperfi.eth/logo.png
  spaces/keeperfi.eth/space.png
Labels: domain, ready to merge

#655 Restrict voting to yYFL holders
  spaces/yflink/index.json
Labels: ready to merge, strategies

#657 Add Cover deployer as a core member for Cover space
  spaces/cover/index.json
Labels: ready to merge

#658 add member
  spaces/yam/index.json
Labels: ready to merge

#659 Add Cyclone Protocol Space
  spaces/cyclonepro.eth/logo.png
  spaces/cyclonepro.eth/space.png
Labels: ready to merge

#656 add unidex logo
  spaces/unidexapp.eth/logo.png
  spaces/unidexapp.eth/space.png
Labels: ready to merge

#599 Update the header color for badger.scss
  skins/badger.scss
Labels: ready to merge

#661 Final bg color fix
  skins/badger.scss
Labels: ready to merge, standby

#660 Add tacoswap
  spaces/domains.json
  spaces/tacoswap.eth/logo.png
  spaces/tacoswap.eth/space.png
Labels: domain, ready to merge

#662 Fix header-bg color
  skins/badger.scss
Labels: ready to merge

#663 Add core cover member
  spaces/cover/index.json
Labels: ready to merge

#665 Update domains.json
  spaces/domains.json
Labels: domain

#666 Add a logo for xDai STAKE space
  spaces/xdaistake.eth/logo.png
  spaces/xdaistake.eth/space.png
Labels: ready to merge

#670 Add images and domain for lrctoken.eth
  spaces/domains.json
  spaces/lrctoken.eth/logo.png
  spaces/lrctoken.eth/space.png
Labels: domain, ready to merge

#676 Add Amp space
  skins/amp.scss
  spaces/amp.eth/logo.png
  spaces/amp.eth/space.png
  spaces/domains.json
Labels: ready to merge

#674 Add SPDR space
  skins/spiderdao.scss
  spaces/domains.json
  spaces/spider-dao.eth/logo.png
  spaces/spider-dao.eth/space.png
Labels: domain, ready to merge

#673 update gainswap logo
  spaces/gainswap.eth/logo.png
  spaces/gainswap.eth/space.png
Labels: invalid

#683 Update SpiderDAO domain entry.
  spaces/domains.json
Labels: domain, ready to merge

#686 Added hypnotube.eth
  spaces/hypnotube.eth/logo.png
  spaces/hypnotube.eth/space.png
Labels: invalid
