Repository snapshot-labs/snapshot-spaces, pull requests merged in 2021-03, with the labels that each got.

#914 add skin and image for Goatcoin
  skins/goatcoin.scss
  spaces/goatcoin.eth/logo.png
  spaces/goatcoin.eth/space.png
Labels: ready to merge

#916 add magicbalancer space
  skins/magicbalancer.scss
  spaces/domains.json
  spaces/magicbalancer.eth/logo.png
  spaces/magicbalancer.eth/space.png
Labels: domain, ready to merge

#917 Adding a strategy to our Ocean Snapshot
  spaces/oceandao/index.json
Labels: ready to merge, strategies

#901 Migrate Tokenlon space
  spaces/aliases.json
  spaces/tokenlon.eth/logo.png
  spaces/tokenlon.eth/space.png
  spaces/tokenlon/index.json
Labels: migration, ready to merge

#918 space for zfogg.eth (images, custom domain)
  spaces/domains.json
  spaces/zfogg.eth/logo.png
  spaces/zfogg.eth/space.png
Labels: domain, ready to merge

#907 Update Yearn space
  skins/yearn.scss
Labels: invalid

#925 Removing voting with OceanMarketplace Staked Tokens: Proper Vote Count not working
  spaces/oceandao/index.json
Labels: strategies

#887 Bamboo spaces
  skins/bamboodefi.scss
  spaces/domains.json
Labels: domain, invalid

#920 Add TCR Space
  skins/tracer.scss
  spaces/tracer.eth/logo.png
  spaces/tracer.eth/space.png
Labels: ready to merge, standby

#926 Migrate synthetix spaces to ENS
  spaces/aliases.json
  spaces/domains.json
  spaces/snxgov.eth/logo.png
  spaces/snxgov.eth/logo1.png
  spaces/snxgov.eth/space.png
  spaces/snxgrants.eth/logo.png
  spaces/snxgrants.eth/logo1.png
  spaces/snxgrants.eth/space.png
  spaces/spartancouncil.eth/logo.png
  spaces/spartancouncil.eth/logo1.png
  spaces/spartancouncil.eth/space.png
  spaces/spotlight.json
  spaces/synthetix/index.json
  spaces/synthetixcouncil/index.json
  spaces/synthetixgrants/index.json
  spaces/synthetixproposal/index.json
  spaces/synthetixproposal/logo.png
  spaces/synthetixproposal/logo1.png
  spaces/synthetixproposal/space.png
Labels: migration, ready to merge

#927 add ensuser.eth
  spaces/domains.json
  spaces/ensuser.eth/logo.png
  spaces/ensuser.eth/space.png
Labels: domain, ready to merge

#930 Update domains.json
  spaces/domains.json
Labels: domain

#931 Add logo and space to eMarket.eth
  spaces/emarket.eth/logo.png
  spaces/emarket.eth/space.png
Labels: ready to merge

#928 ICHI.farm logo update
  spaces/ichi.eth/logo.png
  spaces/ichi.eth/space.png
Labels: ready to merge

#940 Add xcomb.eth
  spaces/domains.json
  spaces/xcomb.eth/logo.png
  spaces/xcomb.eth/space.png
Labels: domain, ready to merge

#939 Fixing logo, adding skin and index file
  skins/visor.scss
  spaces/visor.eth/space.png
Labels: ready to merge

#941 added-logo-manhattan
  spaces/manhattanfinance.eth/logo.png
  spaces/manhattanfinance.eth/space.png
Labels: ready to merge

#943 Adding custom logo for insuretoken.eth space
  spaces/insuretoken.eth/logo.png
  spaces/insuretoken.eth/space.png
Labels: ready to merge

#946 add gov.visor.finance
  spaces/domains.json
Labels: domain

#947 add ruler protocol
  spaces/domains.json
  spaces/rulerprotocol.eth/logo.png
  spaces/rulerprotocol.eth/space.png
Labels: domain

#948 add biopset.eth
  spaces/biopset.eth/logo.png
  spaces/biopset.eth/space.png
Labels: ready to merge

#949 yAxis new logo
  spaces/yaxis/index.json
  spaces/yaxis/logo.png
  spaces/yaxis/space.png
Labels: ready to merge, strategies

#951 Add midasgold space
  spaces/midasgold.eth/logo.png
  spaces/midasgold.eth/space.png
Labels: ready to merge

#955 Added images to quickvote.eth for Quickswap
  spaces/quickvote.eth/logo.png
  spaces/quickvote.eth/space.png
Labels: ready to merge

#952 Add Aqualair Logo
  spaces/aqualair.eth/logo.png
  spaces/aqualair.eth/space.png
Labels: ready to merge

#953 Add ITAM space
  skins/itam.scss
  spaces/domains.json
  spaces/itam.eth/logo.png
  spaces/itam.eth/space.png
Labels: domain, ready to merge

#945 Ethereum4 Snapshot Space
  spaces/ethereum4.eth/logo.png
  spaces/ethereum4.eth/space.png
Labels: ready to merge, standby

#959 Add Radicle
  spaces/gov.radicle.eth/logo.png
  spaces/gov.radicle.eth/space.png
Labels: ready to merge

#960 Add Kangal logo and space image
  spaces/kangal.eth/logo.png
  spaces/kangal.eth/space.png
Labels: ready to merge

#961 Refactored PoolTogether to Dai Prize Pool
  spaces/dai-prize-pool/index.json
  spaces/dai-prize-pool/logo.png
  spaces/dai-prize-pool/space.png
  spaces/pooltogether/logo.png
  spaces/pooltogether/space.png
Labels: ready to merge

#950 Add gvvalue logo
  spaces/gvvalue.eth/logo.png
  spaces/gvvalue.eth/space.png
Labels: ready to merge

#962 Edit yAxis skin
  skins/yaxis.scss
  spaces/yaxis/index.json
Labels: ready to merge

#971 Add domain for gvvalue.eth
  spaces/domains.json
Labels: domain, ready to merge

#977 Add bingocash.fi
  spaces/bingocash.eth/logo.png
  spaces/bingocash.eth/space.png
  spaces/domains.json
Labels: domain, ready to merge

#978 rebrand bscex to launchzone
  spaces/bscex.eth/logo.png
  spaces/bscex.eth/space.png
  spaces/domains.json
Labels: domain, ready to merge

#981 Update domains.json
  spaces/domains.json
Labels: domain, ready to merge

#937 added bears.finance (fbear.eth)
  spaces/domains.json
  spaces/fbear.eth/logo.png
  spaces/fbear.eth/space.png
Labels: domain, standby

#987 Add new logo
  spaces/latticegov.eth/logo.png
  spaces/latticegov.eth/space.png
Labels: ready to merge

#983 add ballena.io
  spaces/ballena.eth/logo.png
  spaces/ballena.eth/space.png
  spaces/domains.json
Labels: domain, ready to merge

#992 Add images and custom domain for Forcedao
  spaces/domains.json
  spaces/forcedao.eth/logo.png
  spaces/forcedao.eth/space.png
Labels: domain, ready to merge

#995 Add Bancor
  spaces/bancornetwork.eth/logo.png
  spaces/bancornetwork.eth/space.png
  spaces/domains.json
  spaces/spotlight.json
Labels: domain, ready to merge

#994 Add avatar and change the skin
  skins/shabushabu.scss
  spaces/shabushabufi.eth/logo.png
  spaces/shabushabufi.eth/space.png
Labels: invalid

#1001 Add alias for migrate my space
  spaces/aliases.json
  spaces/iwan.eth/logo.png
  spaces/iwan.eth/space.png
  spaces/iwan/index.json
Labels: migration, ready to merge

#1000 add cover alias
  spaces/aliases.json
Labels: standby

#1003 Add cryptokombat.eth space
  spaces/cryptokombat.eth/logo.png
  spaces/cryptokombat.eth/space.png
  spaces/domains.json
Labels: domain, ready to merge

#1004 Modify the skin
  skins/iwan.scss
Labels: ready to merge

#1006 Updating oceandao strategy, and migrating oceandao to officialoceandao.eth
  spaces/aliases.json
  spaces/oceandao/index.json
Labels: ready to merge, strategies

#1007 Add 88mph.eth
  spaces/88mph.eth/logo.png
  spaces/88mph.eth/space.png
  spaces/domains.json
Labels: invalid

#1009 officialoceandao.eth ENS migration
  spaces/domains.json
  spaces/officialoceandao.eth/logo.png
  spaces/officialoceandao.eth/space.png
Labels: migration, ready to merge

#1016 Adding KimchiDAO custom domain
  spaces/domains.json
Labels: domain, ready to merge

#1015 Add ILV.GOV space requirements
  spaces/domains.json
  spaces/ilvgov.eth/logo.png
  spaces/ilvgov.eth/space.png
Labels: domain, invalid

#1023 Add Tracer domain
  spaces/domains.json
Labels: domain, ready to merge

#1022 Add curiovoters.eth space domain and images
  spaces/curiovoters.eth/logo.png
  spaces/curiovoters.eth/space.png
  spaces/domains.json
Labels: domain, ready to merge

#1026 Compound space domain and avatar
  spaces/comp-vote.eth/logo.png
  spaces/comp-vote.eth/space.png
  spaces/domains.json
Labels: domain, ready to merge

#1008 Add ARCx Governance Token
  spaces/arcx.eth/logo.png
  spaces/arcx.eth/space.png
  spaces/domains.json
Labels: domain, ready to merge

#1021 Opium Oracles space images and domain
  spaces/domains.json
  spaces/oracles.opiumprotocol.eth/logo.png
  spaces/oracles.opiumprotocol.eth/space.png
Labels: domain, ready to merge

#1027 Update domains.json
  spaces/domains.json
Labels: domain, ready to merge

#1029 Update Trias space
  spaces/trias/index.json
Labels: ready to merge

#1030 feature: Add ballena skin
  skins/ballena.scss
Labels: ready to merge

#1031 Update tusker space
  spaces/domains.json
  spaces/tuskerfinance.eth/logo.png
  spaces/tuskerfinance.eth/space.png
Labels: domain, ready to merge

#1032 Add defiville.eth logos
  spaces/defiville.eth/logo.png
  spaces/defiville.eth/space.png
Labels: ready to merge

#1035 Add Space suni.eth
  spaces/suni.eth/logo.png
  spaces/suni.eth/space.png
Labels: invalid

#1034 Add MACARONSWAP space
  skins/macaronswap.scss
  spaces/aliases.json
  spaces/domains.json
  spaces/macaronswap.eth/logo.png
  spaces/macaronswap.eth/space.png
Labels: domain, ready to merge

#1037 Add domain SUNI
  spaces/domains.json
Labels: domain, ready to merge

#1039 add images and domain
  spaces/domains.json
  spaces/resdx.eth/logo.png
  spaces/resdx.eth/space.png
Labels: domain, ready to merge

#1043 adding saltdao.eth
  spaces/saltdao.eth/logo.png
  spaces/saltdao.eth/space.png
Labels: ready to merge
