Repository snapshot-labs/snapshot-spaces, pull requests merged in 2021-11, with the labels that each got.

#1665 Add $MATE
  skins/index.js
  skins/mate.scss
Labels: invalid

#1676 Update domains.json
  spaces/domains.json
Labels: standby

#1679 Add Pillar alias
  spaces/aliases.json
Labels: migration

#1694 Add custom domain name for carbonpaws.eth
  spaces/domains.json
Labels: invalid

#1710 Update domains.json
  spaces/domains.json
Labels: standby
