Repository snapshot-labs/snapshot-spaces, pull requests merged in 2021-01, with the labels that each got.

#695 Add support for votes.finance
  spaces/votesfinance.eth/logo.png
  spaces/votesfinance.eth/space.png
Labels: ready to merge

#696 add dodo image
  spaces/dodobird.eth/logo1.png
  spaces/dodobird.eth/space.png
Labels: ready to merge

#698 Add BSCEX space
  spaces/bscex.eth/logo.png
  spaces/bscex.eth/space.png
  spaces/domains.json
Labels: domain, ready to merge

#699 Updated proposal threshold and core address
  spaces/debaseonomics/index.json
Labels: ready to merge

#701 Add aria.eth space
  spaces/aria.eth/logo.png
  spaces/aria.eth/space.png
Labels: ready to merge

#702 Updated Rari core addresses
  spaces/rari/index.json
Labels: ready to merge

#703 Add kian.eth space
  spaces/domains.json
Labels: domain, ready to merge

#704 Add 1SD Space
  spaces/1sd.eth/logo.png
  spaces/1sd.eth/space.png
  spaces/domains.json
Labels: domain, ready to merge

#706 Add primitive.eth - primitive.scss, logo.png, and space.png
  skins/primitive.scss
  spaces/primitive.eth/logo.png
  spaces/primitive.eth/space.png
Labels: ready to merge

#707 update COVER token address
  spaces/cover/index.json
Labels: ready to merge

#709 Add mithcash.eth space
  spaces/domains.json
  spaces/mithcash.eth/logo.png
  spaces/mithcash.eth/space.png
Labels: domain, ready to merge

#712 add ndx.eth
  skins/indexed.scss
  spaces/domains.json
  spaces/ndx.eth/logo.png
  spaces/ndx.eth/space.png
Labels: domain, ready to merge

#715 UPDATE OM token address and OM LP token addrres to new V2 token
  spaces/mantra-dao/index.json
Labels: ready to merge

#716 create batdollar space
  spaces/batdollar.eth/logo.png
  spaces/batdollar.eth/space.png
Labels: ready to merge

#718 Fix size of carvefinance logo
  spaces/carvefinance.eth/space.png
Labels: ready to merge

#721 add vote-perp.eth space
  spaces/domains.json
  spaces/vote-perp.eth/logo.png
  spaces/vote-perp.eth/space.png
Labels: domain, ready to merge

#725 feat(spaces): add Ditto.money
  skins/dittomoney.scss
  spaces/dittomoney.eth/logo.png
  spaces/dittomoney.eth/space.png
Labels: invalid

#724 add ironbank.eth space
  spaces/domains.json
  spaces/ironbankfi.eth/logo.png
  spaces/ironbankfi.eth/space.png
Labels: domain

#705 add mind.eth
  spaces/mind.eth/logo.png
  spaces/mind.eth/space.png
Labels: ready to merge

#729 add coffeeswap.eth
  spaces/coffeeswap.eth/logo.png
  spaces/coffeeswap.eth/space.png
  spaces/domains.json
Labels: domain, invalid

#731 Add Empty Set Gold
  skins/emptysetgold.scss
  spaces/domains.json
  spaces/emptysetgold.eth/logo.png
  spaces/emptysetgold.eth/space.png
Labels: domain

#711 Add SpiceDAO Avatar & Space
  spaces/spicedao.eth/logo.png
  spaces/spicedao.eth/space.png
Labels: ready to merge

#735 add derivadao.eth
  skins/derivadao.scss
  spaces/derivadao.eth/logo.png
  spaces/derivadao.eth/space.png
Labels: ready to merge

#736 Change to temporary logo
  spaces/nftx.eth/logo.png
  spaces/nftx.eth/space.png
Labels: ready to merge

#738 Rly registry update jan11
  spaces/rally/index.json
Labels: ready to merge

#739 Empty Set Gold: Style and URL updates.
  skins/emptysetgold.scss
  spaces/domains.json
  spaces/emptysetgold.eth/logo.png
  spaces/emptysetgold.eth/space.png
Labels: domain, ready to merge

#734 move truefi logos to new space
  spaces/truefigov.eth/logo.png
  spaces/truefigov.eth/space.png
Labels: ready to merge

#742 Updated for ESB based on comments
  spaces/emptysetbitcoin.eth/logo1.png
Labels: ready to merge

#743 marsproject.eth commit
  spaces/domains.json
  spaces/marsproject.eth/logo.png
  spaces/marsproject.eth/space.png
Labels: domain, ready to merge

#747 Added vote.mahadao.com logo and custom domain
  spaces/domains.json
  spaces/maha.eth/logo.png
  spaces/maha.eth/space.png
Labels: domain, ready to merge

#745 Add BarnBridge Snapshot config
  skins/barnbridge.scss
  spaces/barnridge.eth/logo.png
  spaces/barnridge.eth/space.png
  spaces/domains.json
Labels: domain, invalid

#752 add skin and logo for evolutionland space
  skins/evoland.scss
  spaces/evoland.eth/logo.png
  spaces/evoland.eth/space.png
Labels: ready to merge

#759 Update domains.json
  spaces/domains.json
Labels: domain

#757 Add Skin and Logo for Benchmark Protocol
  skins/benchmark.scss
  spaces/benchmarkprotocol.eth/logo.png
  spaces/benchmarkprotocol.eth/space.png
Labels: ready to merge

#763 add DSD
  spaces/domains.json
  spaces/dsd.eth/logo.png
  spaces/dsd.eth/space.png
Labels: domain, ready to merge

#768 Move ironbank to a new domain
  spaces/domains.json
Labels: domain

#770 sportx.eth skin and avatar
  skins/sportx.scss
  spaces/domains.json
  spaces/sportx.eth/logo.png
  spaces/sportx.eth/space.png
Labels: domain, ready to merge

#775 Fixed conflicts in index.json
  spaces/iyffinance/index.json
Labels: ready to merge

#776 update squirrel cash logo
  skins/squirrelcash.scss
  spaces/squirrelcash.eth/logo.png
  spaces/squirrelcash.eth/space.png
Labels: ready to merge

#777 add: dexg.eth space
  spaces/dexg.eth/logo.png
  spaces/dexg.eth/space.png
Labels: ready to merge

#780 spicedao.eth update SKIN & Avatar
  skins/spicedao.scss
  spaces/domains.json
  spaces/spicedao.eth/logo.png
  spaces/spicedao.eth/space.png
Labels: invalid

#782 Rly registry update 1/20
  spaces/rally/index.json
Labels: ready to merge

#783 Add more wallets that can create polls
  spaces/mstable/index.json
Labels: ready to merge

#786 Add PEGS space
  spaces/pegscash.eth/logo.png
  spaces/pegscash.eth/space.png
Labels: ready to merge

#789 add: gel.dexg.space
  spaces/gel.dexg.eth/logo.png
  spaces/gel.dexg.eth/space.png
Labels: ready to merge

#791 I've reduced the size of the images to less than 50KB
  spaces/yfdaifinance.eth/logo.png
  spaces/yfdaifinance.eth/space.png
Labels: ready to merge

#787 Removed core member address
  spaces/debaseonomics/index.json
Labels: invalid

#794 Add Neverlose.money avatar and skin
  skins/neverlose.scss
  spaces/neverlose.eth/logo.png
  spaces/neverlose.eth/space.png
Labels: ready to merge

#798 add - stakedao.eth
  spaces/stakedao.eth/logo.png
  spaces/stakedao.eth/space.png
Labels: ready to merge

#799 Prosper.so snapshot page
  spaces/domains.json
  spaces/prosperso.eth/logo.png
  spaces/prosperso.eth/space.png
Labels: ready to merge

#800 add basisgold.eth space
  spaces/basisgold.eth/logo.png
  spaces/basisgold.eth/space.png
Labels: invalid

#801 Add typhoon-cash.eth space
  spaces/typhoon-cash.eth/logo.png
  spaces/typhoon-cash.eth/space.png
Labels: standby

#784 DEXTF material
  skins/dextfprotocol.scss
  spaces/dextfprotocol.eth/logo.png
  spaces/dextfprotocol.eth/space.png
  spaces/domains.json
Labels: standby

#806 Add domain for clapfinance
  spaces/domains.json
Labels: domain

#805 changed contract address
  spaces/finnexus/index.json
Labels: standby

#808 New logo version + strategy
  spaces/dextfprotocol.eth/space.png
Labels: invalid

#809 Setup ens and custom domain for bZx
  spaces/aliases.json
  spaces/domains.json
Labels: domain, migration

#810 Added logo and space images for test space
  spaces/testmytoken.eth/logo.jpg
  spaces/testmytoken.eth/space.jpg
Labels: invalid

#816 Added aventus.eth and domain
  spaces/aventus.eth/logo.png
  spaces/aventus.eth/space.png
  spaces/domains.json
Labels: domain, ready to merge

#817 Add GEAR BPT to MetaFactory Strategies and update logos
  spaces/metafactory/index.json
  spaces/metafactory/logo.png
  spaces/metafactory/space.png
Labels: ready to merge, strategies

#814 add avatar for mushroomsfi.eth
  spaces/mushroomsfi.eth/logo.png
  spaces/mushroomsfi.eth/space.png
Labels: ready to merge

#819 Add metafactory.eth to aliases
  spaces/aliases.json
Labels: migration, ready to merge

#818 Create mStable DAO.eth
  spaces/mstabledao.eth/logo.png
  spaces/mstabledao.eth/space.png
Labels: invalid

#807 Updating AirSwap and adding Rinkeby space
  spaces/airswap/index.json
  spaces/airswap/logo.png
  spaces/airswap/space.png
  spaces/aliases.json
  spaces/domains.json
  spaces/vote-rinkeby.airswap.eth/logo.png
  spaces/vote-rinkeby.airswap.eth/space.png
  spaces/vote.airswap.eth/logo.png
  spaces/vote.airswap.eth/space.png
Labels: migration, standby
