Repository snapshot-labs/snapshot-spaces, pull requests merged in 2021-02, with the labels that each got.

#827 Add monsterslayer custom domain
  spaces/domains.json
Labels: domain

#823 Adding 1btc.eth Space
  spaces/1btc.eth/logo.png
  spaces/1btc.eth/space.png
Labels: ready to merge

#828 Update core member addresses
  spaces/pickle/index.json
Labels: ready to merge

#835 Add Opium logos and domain
  spaces/domains.json
  spaces/opiumprotocol.eth/logo.png
  spaces/opiumprotocol.eth/space.png
Labels: domain

#829 updated balanceOf target to new DHT staking contract
  spaces/aliases.json
  spaces/dhedge/index.json
  spaces/gov.dhedge.eth/logo.png
  spaces/gov.dhedge.eth/logo1.png
  spaces/gov.dhedge.eth/space.png
Labels: migration, ready to merge

#837 Add custom domain for "shabushabufi.eth"
  spaces/dalmatians.eth/logo.png
  spaces/dalmatians.eth/space.png
  spaces/domains.json
Labels: domain

#838 Added alias & need migration for our space
  spaces/aliases.json
Labels: migration

#840 Add avatar
  spaces/kif-gov.eth/logo.png
  spaces/kif-gov.eth/space.png
Labels: ready to merge

#846 Add ILV skin + domain
  skins/ilv.scss
  spaces/domains.json
Labels: domain, ready to merge

#845 Add space for CURE
  spaces/curefarm.eth/logo.png
  spaces/curefarm.eth/space.png
Labels: invalid

#847 added tw33t logo and skin
  skins/tw33t.scss
  spaces/tw33t.eth/logo.png
  spaces/tw33t.eth/space.png
Labels: invalid

#852 Add ilv avatar
  spaces/ilv.eth/logo.png
  spaces/ilv.eth/space.png
Labels: domain, invalid

#855 Add HOPR Genesis DAO space
  spaces/domains.json
  spaces/genesis-dao.hopr.eth/logo.png
  spaces/genesis-dao.hopr.eth/space.png
Labels: domain, ready to merge

#856 Add HOPR skin
  skins/hopr.scss
Labels: ready to merge

#857 Add premia.eth space
  skins/premia.scss
  spaces/domains.json
  spaces/premia.eth/logo.png
  spaces/premia.eth/space.png
Labels: invalid

#859 Feat: Added logo and space for PerlinX
  spaces/domains.json
  spaces/perlinx.eth/logo.png
  spaces/perlinx.eth/space.png
Labels: domain, invalid

#862 thefamoustoken
  spaces/thefamoustoken.eth/logo.png
  spaces/thefamoustoken.eth/space.png
Labels: invalid

#864 Add lido skin
  skins/lido.scss
Labels: invalid

#866 Add invalids
  spaces/achievmintry/index.json
Labels: ready to merge

#865 alchemistcoin.eth
  spaces/alchemistcoin.eth/logo.png
  spaces/alchemistcoin.eth/space.png
  spaces/domains.json
Labels: domain

#870 Update domains.json
  spaces/domains.json
Labels: domain, ready to merge

#872 Add cafeswapfinance.eth space
  spaces/cafeswapfinance.eth/logo.png
  spaces/cafeswapfinance.eth/space.png
Labels: ready to merge

#871 Update domains.json
  spaces/domains.json
Labels: domain, invalid

#854 Added logo and space for bamboodefi
  spaces/bamboodefi.eth/logo.png
  spaces/bamboodefi.eth/space.png
Labels: invalid

#879 Update ACryptoS logo and strategy
  spaces/acryptos/index.json
  spaces/acryptos/logo.png
  spaces/acryptos/space.png
Labels: ready to merge, strategies

#889 add Klondike.eth
  spaces/klondike.eth/logo.png
  spaces/klondike.eth/space.png
Labels: invalid

#890 update new logos
  spaces/baovotes.eth/logo.png
  spaces/baovotes.eth/space.png
Labels: ready to merge

#891 Update domains.json
  spaces/domains.json
Labels: domain, ready to merge

#896 Add PancakeBunny Space
  spaces/domains.json
  spaces/pancakebunny.eth/logo.png
  spaces/pancakebunny.eth/space.png
Labels: domain, ready to merge

#898 Add mcl-multiplierfinance.eth space
  spaces/domains.json
  spaces/mcl-multiplierfinance.eth/ space.png
  spaces/mcl-multiplierfinance.eth/logo.png
Labels: domain, ready to merge

#899 Pull request to add image to eublas.eth
  spaces/eublas.xyz/logo.png
  spaces/eublas.xyz/space.png
Labels: ready to merge

#905 add iFARM to Harvest Finance config
  spaces/farm/index.json
Labels: ready to merge, strategies

#904 Add santiment
  skins/santiment.scss
  spaces/domains.json
  spaces/santiment.eth/logo.png
  spaces/santiment.eth/logo1.png
  spaces/santiment.eth/space.png
Labels: domain, ready to merge

#906 add candy finance logo
  spaces/candyfinance.eth/logo.png
  spaces/candyfinance.eth/space.png
Labels: ready to merge

#910 Update domains.json
  spaces/domains.json
Labels: domain, ready to merge

#909 fix iFARM; migrate to ENS
  spaces/aliases.json
  spaces/farm/index.json
  spaces/farm/logo.png
  spaces/farm/logo1.png
  spaces/farm/space.png
  spaces/harvestfi.eth/logo.png
  spaces/harvestfi.eth/space.png
Labels: ready to merge

#912 add alpacafinance.eth space
  skins/alpaca.scss
  spaces/alpacafinance.eth/logo.png
  spaces/alpacafinance.eth/space.png
  spaces/domains.json
Labels: domain, ready to merge

#915 Create easybake.eth
  skins/easybake.scss
  spaces/easybake.eth/logo.png
  spaces/easybake.eth/space.png
Labels: invalid
