Repository snapshot-labs/snapshot-spaces, pull requests merged in 2022-01, with the labels that each got.

#1791 Migrate dForce space to ENS.
  spaces/aliases.json
Labels: invalid, migration

#1793 Update Tres Leches Cake Domain, issue on ens
  spaces/domains.json
Labels: standby

#1800 Adding vote.hectordao.com
  spaces/domains.json
Labels: invalid

#1795 Update domains.json
  spaces/domains.json
Labels: invalid

#1803 Add LongTerm Finance skin
  skins/index.js
  skins/longterm.scss
Labels: invalid

#1814 update domain
  spaces/domains.json
Labels: invalid

#1816 update: add skin styles
  skins/index.js
  skins/totemearth.scss
Labels: invalid

#1822 Update aliases.json + domains.json
  spaces/aliases.json
  spaces/domains.json
Labels: migration

#1818 Add vote.kapital.gg to spaces/domains.json
  spaces/domains.json
Labels: invalid

#1833 Added theartistdao.com address
  spaces/domains.json
Labels: invalid

#1840 Add vote.oceanclub.io to domains
  spaces/domains.json
Labels: invalid

#1853 Update domains.json
  spaces/domains.json
Labels: invalid
